sudo: false

language: python

python:
  - 3.6.3

install:
  - pip install -r requirements.txt
  - pip install codecov
  - bash scripts/create_settings.sh

script:
  - nosetests --with-coverage --verbosity=2

after_success:
- codecov